name: Automate Build, deploy 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{c35ad4bc-27b7-41ac-a3cf-3844268a8c01}}
          heroku_app_name: "cargo-cs5500" #Must be unique in Heroku
          heroku_email: "wangyafei1208@gmail.com"
      
      - name: Run the build
        run: |
          cd CarGO/
          echo "Making the build...."
          npm install
          
      - name: Deploy
        run: |
          cd CarGO/
          git init
          heroku git:remote -a cargo-cs5500
          git add .
          git commit -am "make it better"
          git push heroku master -f