name: Automate Build 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
    - main

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Run the build
        run: |
          cd CarGO/
          echo "Making the build...."
          npm install
          